### ISSUE TITLE
Read file encoding error

### ISSUE THREAD

**Issue by hram** [dmitry-zaitsev/LayoutVerifier#3]
Hi
I have problem with Russian character
All tests pass if I run tests from android studio
But fails some test with Russian characters on screen if I run tests from gradle task
![image](https://user-images.githubusercontent.com/2150637/82658045-0c2ea180-9c2f-11ea-96ef-8d453039e5a4.png)

And actual/snapshot is correct in has encoding UTF-8
If I open snapshot file in notepad++ or AS I see all Russian characters correctly

**Comment by dmitry-zaitsev** [comment]
Thank you for reporting this. I will try to reproduce the issue.

**Comment by dmitry-zaitsev** [comment]
I was able to reproduce and fix the issue, will publish fix as version `1.1.1` after CI run will finish.
